version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install deps
          command: pip install -r requirements.txt
      - run:
          name: Simple test
          command: python -c "print('FastAPI test passed')"

  build_run_test_docker:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout

      - run:
          name: Docker Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            docker build -t fastapi-circleci-demo .
            docker tag fastapi-circleci-demo ${DOCKERHUB_USERNAME}/fastapi-circleci-demo:latest

      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8000:8000 --name fastapi_container fastapi-circleci-demo
            sleep 5

      - run:
          name: Test FastAPI endpoint
          command: curl -f http://localhost:8000/health

      - run:
          name: Push Docker image to DockerHub
          command: |
            docker push ${DOCKERHUB_USERNAME}/fastapi-circleci-demo:latest

workflows:
  fastapi_pipeline:
    jobs:
      - build_and_test
      - build_run_test_docker:
          requires:
            - build_and_test
